<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta http-equiv="content-type" content="<?php bloginfo('html_type'); ?>; charset=<?php bloginfo('charset'); ?>" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="HandheldFriendly" content="true" />
  <link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
  <?php wp_head(); ?>
  
  <link rel="stylesheet" href="/app/themes/frogspark/scss/dist/bundle.min.css?v=<?php echo time(); ?>" type="text/css" media="all" />
  <script src="/app/themes/frogspark/js/dist/bundle.min.js?v=<?php echo time(); ?>"></script>

  <!-- Favicon generated by: https://www.favicon-generator.org -->
  <link rel="apple-touch-icon" sizes="57x57" href="/app/themes/frogspark/fav.ico/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/app/themes/frogspark/fav.ico/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/app/themes/frogspark/fav.ico/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/app/themes/frogspark/fav.ico/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/app/themes/frogspark/fav.ico/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/app/themes/frogspark/fav.ico/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/app/themes/frogspark/fav.ico/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/app/themes/frogspark/fav.ico/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/app/themes/frogspark/fav.ico/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/app/themes/frogspark/fav.ico/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/app/themes/frogspark/fav.ico/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/app/themes/frogspark/fav.ico/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/app/themes/frogspark/fav.ico/favicon-16x16.png">
  <link rel="manifest" href="/app/themes/frogspark/fav.ico/manifest.json">
  <meta name="msapplication-TileImage" content="/app/themes/frogspark/fav.ico/ms-icon-144x144.png">

  <!-- Google Analytics generated by: https://analytics.google.com/analytics/web/ -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=<?php if (get_field('google_analytics_id', 'option')): the_field('google_analytics_id', 'option'); endif; ?>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '<?php if (get_field('google_analytics_id', 'option')): the_field('google_analytics_id', 'option'); endif; ?>');
  </script>

  <!-- Cookie popup generated by: https://cookieconsent.insites.com/download/ -->
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
  <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
  <script>
    window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {"background": "#000000"},
        "button": {"background": "#FFFFFF", "text": "#000"}
      },
      "position": "bottom-left",
      "content": {"href": "/cookie-policy/"}
    })});
  </script>
  
  <style>
    
    .cc-message {
      color: #fff !important;
    }
    
  </style>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js" integrity="sha256-NXRS8qVcmZ3dOv3LziwznUHPegFhPZ1F/4inU7uC8h0=" crossorigin="anonymous"></script>
  
  <script>
    
    $(document).ready(function(){
      
      $(".scrolllink").click(function( event ) {
        event.preventDefault();
        //alert('t');
        $("html, body").animate({ scrollTop: $($(this).attr("href")).offset().top - 80 }, 500);
      });
      
      function openMenu(open) { $('#burger').toggleClass('open', open); $('#navigation-mobile ul').toggleClass('open', open); }
      var open = false;
      $('#burger').click(function() { open = !open; openMenu(open); });


      $(window).scroll(function(){
        var scrollPos = $(document).scrollTop();
        
        if(scrollPos > 5)
        {
          $("#header").addClass("stick");
        }
        else
        {
          $("#header").removeClass("stick");
        }
      });
      
      $('.alt-slider').slick({
        dots: false,
        infinite: false,
        speed: 300,
        slidesToShow:4,
        slidesToScroll: 1,
        adaptiveHeight: true,
        prevArrow: $('.prev'),
        nextArrow: $('.next'),
        responsive: [
          {
            breakpoint: 1024,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 1,
              infinite: true,
            }
          },
          {
            breakpoint: 600,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1
            }
          },
          {
            breakpoint: 480,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1
            }
          }
          // You can unslick at a given breakpoint now by adding:
          // settings: "unslick"
          // instead of a settings object
        ]
      });
      
      $('.journey-slider').slick({
        dots: false,
        infinite: true,
        speed: 300,
        slidesToShow:3,
        slidesToScroll: 1,
        adaptiveHeight: true,
        prevArrow: $('.prev'),
        nextArrow: $('.next'),
        responsive: [
          {
            breakpoint: 1024,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 1,
              infinite: true,
            }
          },
          {
            breakpoint: 600,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1
            }
          },
          {
            breakpoint: 480,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1
            }
          }
          // You can unslick at a given breakpoint now by adding:
          // settings: "unslick"
          // instead of a settings object
        ]
      });
      
      $('.press-slider').slick({
        dots: false,
        infinite: true,
        speed: 300,
        slidesToShow:6,
        slidesToScroll: 1,
        adaptiveHeight: true,
        prevArrow: $('.prevv'),
        nextArrow: $('.nextt'),
        responsive: [
          {
            breakpoint: 1024,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 1,
              infinite: true,
            }
          },
          {
            breakpoint: 600,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 1
            }
          },
          {
            breakpoint: 480,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 1
            }
          }
          // You can unslick at a given breakpoint now by adding:
          // settings: "unslick"
          // instead of a settings object
        ]
      });
      
    });
    
  </script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css" integrity="sha256-UK1EiopXIL+KVhfbFa8xrmAWPeBjMVdvYMYkTAEv/HI=" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" integrity="sha256-GqiEX9BuR1rv5zPU5Vs2qS/NSHl1BJyBcjQYJ6ycwD4=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js" integrity="sha256-pQBbLkFHcP1cy0C8IhoSdxlm0CtcH5yJ2ki9jjgR03c=" crossorigin="anonymous"></script>
  
</head>
<body <?php body_class(); ?>>